### ISSUE TITLE
Substitute <br /> with newlines

### ISSUE THREAD

**Issue by giuliocorradini** [mc-cat-tty/PlaceRank#22]

**Comment by giuliocorradini** [comment]
Add a Whoosh filter to eliminate these unwanted tokens

**Comment by mc-cat-tty** [comment]
Done online with a66d915303bcf0ed0043dc28f85bc7fc7261e310
Filter still needed for indexing

**Comment by giuliocorradini** [comment]
63d354c0f1f8cfa1fa0c786dcc53cd7076c0d4f2
