### ISSUE TITLE
Support runtime edit of Whoosh analyzer

### ISSUE THREAD

**Issue by giuliocorradini** [mc-cat-tty/PlaceRank#3]
To speed up things, we should provide a convenient method to change the corpus analyzer on the fly.

Right now you have to redefine the `getDefaultAnalyzer`, which is referenced in `placerank.logic_views.DocumentLogicView` but this makes it impossible to change the default analyzer at runtime.

We could change the function code for getDefaultAnalyzer by making its `func_code` field referencing the `func_code` of another ad-hoc function, but I think this is somewhat inelegant and convoluted.

Maybe let's make a factory that returns the appropriate analyzer. Another problem arises: the call to getDefaultAnalyzer, or this virtual factory, is inside the constructor of a class field. I think we should move the inverted index schema outside and create a separate class.

**Comment by mc-cat-tty** [comment]
A different analyzer implies recreating the index; it's a non-common behaviour.
Whatever, IoC patterns are all ok for this task.

**Comment by giuliocorradini** [comment]
We are going to test different preprocessing, could leaving everything as it is lead to more difficulties in managing different versions of the code?

Extracting the schema from DocumentLogicView is a matter of few changes, let me propose an implementation

**Comment by giuliocorradini** [comment]
See cfe910b5bba3f1e7d2e5a0bfc171712cc842f60f on refactor_schema_logic_view branch

An exception in the LemmaFilter is arised when trying to build the inverted index, but I think it's got nothing to do with the schema refactoring.

**Comment by giuliocorradini** [comment]
Support is complete with a89869a7 and two examples are provided in `retrieval.ipynb`.

`ANALYZER_LEMMATIZER` was commented out, as well as `LemmaFilter`, since it caused problems in the preprocessing stage even though different analyzers were used.

We need to check for the correctness of preprocessing output.
