### ISSUE TITLE
Cache listings

### ISSUE THREAD

**Issue by giuliocorradini** [mc-cat-tty/PlaceRank#7]
Cache listings when first downloading it, since different inverted index buildings require to download the dataset each time and on slow connections can take up to a minute of total processing time.

**Comment by mc-cat-tty** [comment]
Closed with f1b02e6cfbe27940ec011e04f5c9f894ec12d5cf

Index build time has been sped up by 25% [take it with a grain of salt, it's relative to my testing environment]
